FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y docker.io \
    && groupmod -g 1001 docker \ 
    && usermod -aG docker jenkins

RUN curl -LO "https://dl.k8s.io/release/v1.31.4/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl \
    && rm kubectl

USER jenkins